#!/usr/bin/env python3
"""Serve the local pin-and-project dashboard for conditional wick trajectories.

The service intentionally runs separately from the existing generic Rust
nearest-neighbour dashboard. It never overwrites its files or binds its port.
Each API request calls the already-validated V1 selector with a temporary
output file, so the displayed paths remain generated by the same transparent
historical-episode engine used in the research artifacts.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
import threading
import time
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse

import pandas as pd
import numpy as np

from build_conditional_path_library import (
    FEATURE_COLUMNS,
    detect_strict_signals,
    read_five_minute_file,
    resample_to_fifteen_minutes,
    utc_iso,
)
from build_conditional_path_scenarios import normalized_price, parse_utc, state_for_live_path
from refresh_futures_klines import RefreshResult, exchange_server_time_ms, refresh_source, source_snapshot
from train_conditional_wick_v2 import load_model_bundle, predict_from_observable_state


ROOT = Path(__file__).resolve().parent
ASSETS = ("ETHUSDT", "BTCUSDT")
TIMEFRAMES = ("5m", "15m")
DEFAULT_SIGNAL = {"asset": "ETHUSDT", "timeframe": "5m", "signal_time": "2026-09-16T18:35:00Z"}


HTML = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Conditional Wick Paths</title>
  <script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>
  <style>
    :root { --bg:#0b1118; --panel:#111b26; --line:#26394c; --text:#e7eef5; --muted:#93a5b7; --amber:#eca846; --teal:#38b7a6; --violet:#9497f8; --rust:#dc7954; --danger:#f08a7a; }
    * { box-sizing:border-box; }
    body { margin:0; background:radial-gradient(ellipse 100% 70% at 50% -20%,#1a2b39 0%,var(--bg) 58%); color:var(--text); font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; min-height:100vh; }
    main { width:min(1450px,calc(100% - 32px)); margin:0 auto; padding:28px 0 36px; }
    header { display:flex; justify-content:space-between; align-items:start; gap:20px; padding:4px 0 22px; }
    .eyebrow { color:var(--amber); font-size:11px; font-weight:800; letter-spacing:.14em; text-transform:uppercase; }
    h1 { margin:5px 0 5px; font-size:clamp(25px,3vw,40px); line-height:1.08; letter-spacing:-.035em; }
    .sub { color:var(--muted); max-width:760px; margin:0; }
    .stamp { border:1px solid var(--line); border-radius:999px; padding:7px 11px; color:var(--muted); white-space:nowrap; font-size:12px; }
    .control { border:1px solid var(--line); background:rgba(17,27,38,.92); border-radius:15px; padding:16px; display:grid; grid-template-columns:120px 100px minmax(190px,1fr) minmax(240px,1.2fr) auto; gap:10px; align-items:end; box-shadow:0 18px 45px rgba(0,0,0,.18); }
    label { color:var(--muted); display:grid; gap:6px; font-size:11px; font-weight:750; letter-spacing:.06em; text-transform:uppercase; }
    select,input,button { font:inherit; }
    select,input { color:var(--text); background:#0c151f; border:1px solid #30465a; border-radius:9px; min-height:40px; padding:0 10px; outline:none; }
    select:focus,input:focus { border-color:var(--amber); box-shadow:0 0 0 3px rgba(236,168,70,.13); }
    button { cursor:pointer; border:0; border-radius:9px; min-height:40px; padding:0 15px; color:#101820; font-weight:800; background:var(--amber); transition:transform .16s ease,filter .16s ease; }
    button:hover { transform:translateY(-1px); filter:brightness(1.06); }
    button:disabled { cursor:wait; opacity:.6; transform:none; }
    .status { min-height:24px; color:var(--muted); margin:12px 0 12px; }
    .status.error { color:var(--danger); }
    .layout { display:grid; grid-template-columns:minmax(0,1fr) 310px; gap:16px; }
    .panel { border:1px solid var(--line); border-radius:15px; background:rgba(17,27,38,.9); overflow:hidden; }
    .chart-head { padding:14px 17px 11px; border-bottom:1px solid var(--line); display:flex; justify-content:space-between; gap:16px; align-items:start; }
    .chart-head h2 { margin:0; font-size:15px; letter-spacing:-.015em; }
    .chart-head p { color:var(--muted); font-size:12px; margin:3px 0 0; }
    #chart { height:550px; width:100%; }
    .sidebar { display:grid; gap:16px; align-content:start; }
    .risk { padding:15px; }
    .risk h2 { margin:0 0 11px; font-size:13px; color:var(--muted); letter-spacing:.07em; text-transform:uppercase; }
    .route-grid { display:grid; gap:9px; }
    .route { --route:#fff; position:relative; text-align:left; color:var(--text); background:#0d1721; border:1px solid #2b4053; overflow:hidden; padding:12px; min-height:121px; }
    .route[aria-pressed="true"] { border-color:var(--route); box-shadow:0 0 0 1px color-mix(in srgb,var(--route) 40%,transparent); }
    .route::after { content:""; position:absolute; bottom:0; left:0; height:3px; width:var(--rail); background:var(--route); }
    .route-top { display:flex; justify-content:space-between; gap:8px; align-items:baseline; }
    .route-top b { font-size:15px; } .route-top span { color:var(--route); font-size:11px; font-weight:800; }
    .route p { color:var(--muted); font-size:11px; margin:5px 0 9px; min-height:29px; }
    .route-metrics { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:7px; }
    .route-metrics label { font-size:9px; letter-spacing:.04em; } .route-metrics strong { display:block; font-size:13px; margin-top:1px; }
    .state { padding:15px; } .state h2 { margin:0 0 10px; font-size:13px; color:var(--muted); letter-spacing:.07em; text-transform:uppercase; }
    .metric { display:flex; align-items:baseline; justify-content:space-between; border-top:1px solid #233448; padding:9px 0; gap:12px; }
    .metric span { color:var(--muted); font-size:12px; } .metric b { font-size:13px; text-align:right; }
    .v2 { padding:15px; }
    .v2 h2 { margin:0 0 5px; font-size:13px; color:var(--muted); letter-spacing:.07em; text-transform:uppercase; }
    .v2-kicker { color:#bdc9d5; font-size:11px; margin:0 0 10px; }
    .v2-block { border-top:1px solid #233448; padding:9px 0; display:grid; gap:3px; }
    .v2-block span { color:var(--muted); font-size:11px; }
    .v2-block em { color:#70859a; font-style:normal; }
    .v2-block strong { color:#eef3f7; font-size:13px; }
    .v2-block i { color:#7e91a4; font-style:normal; }
    .v2-calibration { color:#9db0c2; font-size:11px; line-height:1.45; padding-top:9px; border-top:1px solid #233448; }
    .v2-caution { color:#f0c183; font-size:11px; line-height:1.42; margin-top:9px; }
    .v2-unavailable { color:#93a5b7; font-size:12px; line-height:1.5; padding-top:7px; }
    .notice { border-left:3px solid var(--amber); margin-top:16px; padding:11px 13px; background:rgba(236,168,70,.08); color:#c9d4de; font-size:12px; }
    .source { color:var(--muted); font-size:11px; margin:10px 0 0; }
    footer { color:#71869a; font-size:11px; margin-top:15px; text-align:center; }
    a { color:#aeb4ff; }
    @media (max-width:1050px) { .layout { grid-template-columns:1fr; } .sidebar { grid-template-columns:repeat(2,minmax(0,1fr)); } .risk { grid-row:span 2; } }
    @media (max-width:700px) { main { width:min(100% - 20px,1450px); padding-top:18px; } header { display:block; } .stamp { display:inline-block; margin-top:12px; } .control { grid-template-columns:1fr 1fr; } .control label:last-of-type { grid-column:1/-1; } .control button { grid-column:1/-1; } .sidebar { grid-template-columns:1fr; } #chart { height:420px; } }
    @media (prefers-reduced-motion:reduce) { * { transition:none!important; } }
  </style>
</head>
<body>
  <main>
    <header>
      <div><div class="eyebrow">conditional wick-fill instrument · v1</div><h1>Pin a wick. Inspect real historical paths.</h1><p class="sub">Choose an unfilled strict wick candle. The engine matches its live state against completed historical episodes, then draws three actual, rescaled candle paths to the wick target.</p></div>
      <div class="stamp" id="asOf">Loading data snapshot…</div>
    </header>
    <form class="control" id="controls">
      <label>Asset<select id="asset"><option>ETHUSDT</option><option>BTCUSDT</option></select></label>
      <label>Timeframe<select id="timeframe"><option>5m</option><option>15m</option></select></label>
      <label>Recent unfilled wick<select id="signalPicker" aria-label="Recent unfilled strict wick signals"><option value="">Loading candidates…</option></select></label>
      <label>Signal time (UTC)<input id="signalTime" spellcheck="false" value="2026-09-16T18:35:00Z" aria-describedby="timeHelp"></label>
      <button id="project" type="submit">Project paths</button>
    </form>
    <p class="source" id="timeHelp">Pick a current unfilled strict wick or paste any ISO UTC strict-wick candle. Every manual pin is revalidated by the engine.</p>
    <div class="status" id="status" aria-live="polite">Loading the default pinned signal…</div>
    <section class="layout">
      <article class="panel"><div class="chart-head"><div><h2 id="chartTitle">Conditional route</h2><p id="chartNote">Historical candles left; selected conditional path right.</p></div><span class="stamp" id="targetBadge">Wick target —</span></div><div id="chart"></div></article>
      <aside class="sidebar"><section class="panel risk"><h2>Scenario routes</h2><div class="route-grid" id="routes"></div></section><section class="panel state"><h2>Observed state</h2><div id="state"></div></section><section class="panel v2"><h2>V2a calibrated ranges</h2><div id="v2"></div></section></aside>
    </section>
    <div class="notice">These paths are conditional on eventual clean wick fill. They are scenario references for time and risk sizing—not an unconditional probability, price target, or trade instruction.</div>
    <footer>Chart engine: <a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">TradingView Lightweight Charts™</a> · separate local service; no modification to the existing generic Rust dashboard.</footer>
  </main>
  <script>
  (() => {
    const colors={fast:'#38b7a6',normal:'#9497f8',extreme:'#dc7954'};
    const labels={fast:'Fast',normal:'Normal',extreme:'Extreme'};
    let data=null, chart=null, actual=null, projected=null, targetLine=null;
    let refreshStatus=null, knownDataVersion=null, projectionInFlight=false;
    const q=id=>document.getElementById(id);
    const money=value=>'$'+Number(value).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
    const pct=value=>`${Number(value).toFixed(2)}%`;
    const share=value=>`${(Number(value)*100).toFixed(0)}%`;
    const duration=bars=>{ const minutes=Number(bars)*Number(data.pinned_signal.timeframe.replace('m','')); if(minutes>=1440)return `${(minutes/1440).toFixed(1)}d`; if(minutes>=60)return `${Math.round(minutes/60)}h`; return `${Math.max(1,Math.round(minutes))}m`; };
    const berlin=seconds=>new Date(Number(seconds)*1000).toLocaleString('en-GB',{timeZone:'Europe/Berlin',dateStyle:'medium',timeStyle:'short'});
    function setStatus(message,error=false){ q('status').textContent=message; q('status').className='status'+(error?' error':''); }
    function refreshCountdown(milliseconds){const seconds=Math.max(0,Math.ceil(milliseconds/1000)),minutes=Math.floor(seconds/60);return `${String(minutes).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
    function renderRefreshStamp(){
      const node=q('asOf'), source=refreshStatus?.sources?.[q('asset').value];
      const asOf=source?.last_closed_candle_open_time_utc||data?.current_state?.as_of_open_time_utc;
      const snapshot=asOf?`Snapshot closes ${asOf.replace('T',' ').replace('Z',' UTC')}`:'Snapshot loading';
      if(!refreshStatus){node.textContent=snapshot;return;}
      let cycle='refresh scheduling…';
      if(!refreshStatus.enabled)cycle='live refresh paused';
      else if(refreshStatus.in_progress)cycle='refreshing completed candles…';
      else if(refreshStatus.next_refresh_utc)cycle=`next refresh in ${refreshCountdown(Date.parse(refreshStatus.next_refresh_utc)-Date.now())}`;
      if(refreshStatus.last_error)cycle+=' · last refresh needs retry';
      node.textContent=`${snapshot} · ${cycle}`;
    }
    function ensureChart(){
      if(chart) return;
      if(!window.LightweightCharts){ setStatus('Chart library did not load. Check internet access and refresh.',true); return; }
      const node=q('chart');
      chart=LightweightCharts.createChart(node,{layout:{background:{color:'#111b26'},textColor:'#aab8c5',fontFamily:getComputedStyle(document.body).fontFamily},grid:{vertLines:{color:'rgba(48,64,82,.48)'},horzLines:{color:'rgba(48,64,82,.48)'}},rightPriceScale:{borderColor:'#304052'},timeScale:{borderColor:'#304052',timeVisible:true,secondsVisible:false},crosshair:{vertLine:{color:'#60748a',labelBackgroundColor:'#263545'},horzLine:{color:'#60748a',labelBackgroundColor:'#263545'}}});
      actual=chart.addSeries(LightweightCharts.CandlestickSeries,{upColor:'#68c4b4',downColor:'#d27571',borderVisible:false,wickUpColor:'#68c4b4',wickDownColor:'#d27571'});
      projected=chart.addSeries(LightweightCharts.CandlestickSeries,{upColor:colors.normal,downColor:colors.normal,borderUpColor:colors.normal,borderDownColor:colors.normal,wickUpColor:colors.normal,wickDownColor:colors.normal});
      new ResizeObserver(entries=>{for(const entry of entries)chart.applyOptions({width:entry.contentRect.width,height:entry.contentRect.height});}).observe(node);
    }
    function selectScenario(name){
      if(!data) return; const item=data.scenarios.find(x=>x.name===name); if(!item) return;
      document.querySelectorAll('.route').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.name===name)));
      const color=colors[name]; projected.applyOptions({upColor:color,downColor:color,borderUpColor:color,borderDownColor:color,wickUpColor:color,wickDownColor:color}); projected.setData(item.projected_candles);
      q('chartTitle').textContent=`${labels[name]} route — conditional historical trajectory`;
      q('chartNote').textContent=`${duration(item.remaining_to_fill_bars)} remaining · ${item.historical_asset} ${item.historical_timeframe} analogue · terminal wick touch ${berlin(item.projected_candles.at(-1).time+Number(data.pinned_signal.timeframe.replace('m',''))*60)}`;
      chart.timeScale().fitContent();
    }
    function renderV2(risk){
      const node=q('v2');
      if(!risk || !risk.available){node.innerHTML=`<div class="v2-unavailable">${risk?.reason||'V2a diagnostic is unavailable for this pin.'}</div>`;return;}
      const prediction=risk.prediction?.quantiles, remaining=prediction?.remaining_bars, away=prediction?.future_max_away_pct;
      if(!remaining||!away){node.innerHTML='<div class="v2-unavailable">V2a returned an incomplete diagnostic response.</div>';return;}
      const calibration=risk.calibration||{}, coverage=risk.state_coverage||{}, ratio=value=>value==null?'—':`${(Number(value)*100).toFixed(1)}%`;
      const coverageWarning=coverage.elapsed_within_training_snapshot_range===false?`<div class="v2-caution">This pin is ${Number(coverage.elapsed_bars).toLocaleString()} bars after the signal, beyond V2a's largest trained snapshot offset of ${Number(coverage.max_training_snapshot_elapsed_bars).toLocaleString()} bars. Treat its ranges as an extrapolation, not a calibrated live range.</div>`:'';
      node.innerHTML=`<p class="v2-kicker">${risk.estimator}. Quantiles are conditional on historical clean fills.</p><div class="v2-block"><span>Remaining time to wick touch <em>p10 / p50 / p90</em></span><strong>${duration(remaining.p10)} <i>/</i> ${duration(remaining.p50)} <i>/</i> ${duration(remaining.p90)}</strong></div><div class="v2-block"><span>Future max move-away <em>p10 / p50 / p90</em></span><strong>${pct(away.p10)} <i>/</i> ${pct(away.p50)} <i>/</i> ${pct(away.p90)}</strong></div><div class="v2-calibration">Chronological holdout: ${Number(calibration.holdout_snapshot_count||0).toLocaleString()} snapshots. Time p10–p90 captured ${ratio(calibration.remaining_p10_p90_observed_coverage)}; move-away p10–p90 captured ${ratio(calibration.future_away_p10_p90_observed_coverage)} (80% nominal).</div><div class="v2-caution">Do not treat future move-away p10 as a sizing floor: it realized only ${ratio(calibration.future_away_p10_observed_coverage)} of later cases against a 10% target.</div>`;
    }
    function render(next){
      data=next; ensureChart(); if(!chart) return;
      renderRefreshStamp();
      q('targetBadge').textContent=`Wick target ${money(data.pinned_signal.wick_target)}`;
      actual.setData(data.actual_candles); if(targetLine) actual.removePriceLine(targetLine); targetLine=actual.createPriceLine({price:data.pinned_signal.wick_target,color:'#eca846',lineWidth:2,lineStyle:LightweightCharts.LineStyle.Dashed,axisLabelVisible:true,title:'wick target'});
      const routes=q('routes'); routes.replaceChildren();
      data.scenarios.forEach((item,index)=>{const button=document.createElement('button');button.type='button';button.className='route';button.dataset.name=item.name;button.style.setProperty('--route',colors[item.name]);button.style.setProperty('--rail',`${Math.max(8,Math.min(100,item.joint_risk_percentile*100))}%`);button.setAttribute('aria-pressed',String(index===1));button.innerHTML=`<div class="route-top"><b>${labels[item.name]}</b><span>risk p${Math.round(item.joint_risk_percentile*100)}</span></div><p>${item.description}</p><div class="route-metrics"><div><label>to wick touch</label><strong>${duration(item.remaining_to_fill_bars)}</strong></div><div><label>future move-away</label><strong>${pct(item.future_max_away_move_pct)}</strong></div><div><label>tail ≥ this</label><strong>${share(item.matched_cohort_tail_at_or_above_fraction)}</strong></div></div>`;button.addEventListener('click',()=>selectScenario(item.name));routes.append(button);});
      const stateRows=[['Direction',data.pinned_signal.direction.replace('_',' ')],['Current move away',pct(data.current_state.current_move_pct)],['Peak move away',pct(data.current_state.peak_move_pct)],['Drawdown from peak',pct(data.current_state.drawdown_from_peak_pct)],['Elapsed',`${Math.round(data.current_state.elapsed_minutes/60)}h`],['Matched 5m paths',data.library.same_timeframe_trajectory_candidates_before_signal.toLocaleString()],['Cohort P50 remaining',`${Math.round(data.cohort_distribution.remaining_time_to_fill_minutes.p50/60)}h`]];
      q('state').innerHTML=stateRows.map(([k,v])=>`<div class="metric"><span>${k}</span><b>${v}</b></div>`).join('');
      renderV2(data.v2_risk);
      selectScenario('normal');
    }
    async function request(){
      if(projectionInFlight)return;
      projectionInFlight=true;
      const asset=q('asset').value, timeframe=q('timeframe').value, signal_time=q('signalTime').value.trim();
      q('project').disabled=true; setStatus('Searching resolved historical paths and rebuilding three real candle scenarios…');
      try { const response=await fetch(`/api/scenarios?asset=${encodeURIComponent(asset)}&timeframe=${encodeURIComponent(timeframe)}&signal_time=${encodeURIComponent(signal_time)}`); const payload=await response.json(); if(!response.ok)throw new Error(payload.error||'Request failed'); render(payload); setStatus(`Loaded ${payload.pinned_signal.asset} ${payload.pinned_signal.timeframe} ${payload.pinned_signal.direction.replace('_',' ')} pinned at ${payload.pinned_signal.signal_open_time_utc}.`); }
      catch(error){setStatus(error.message||String(error),true);}
      finally{q('project').disabled=false;projectionInFlight=false;}
    }
    async function loadSignals({preferFirst=false}={}){
      const asset=q('asset').value,timeframe=q('timeframe').value,picker=q('signalPicker'); picker.disabled=true; picker.replaceChildren(new Option('Loading candidates…',''));
      try { const response=await fetch(`/api/signals?asset=${encodeURIComponent(asset)}&timeframe=${encodeURIComponent(timeframe)}`); const payload=await response.json(); if(!response.ok)throw new Error(payload.error||'Could not load candidate signals');
        picker.replaceChildren(); if(!payload.signals.length){picker.append(new Option('No unfilled strict signals in recent scan','')); return;}
        payload.signals.forEach((signal,index)=>{const label=`${signal.signal_time_utc} · ${signal.direction.replace('_',' ')} · ${pct(signal.current_move_pct)} away`;picker.append(new Option(label,signal.signal_time_utc,index===0,index===0));});
        const input=q('signalTime'); const matching=payload.signals.find(signal=>signal.signal_time_utc===input.value.trim());
        if(matching){picker.value=matching.signal_time_utc;} else if(preferFirst){input.value=payload.signals[0].signal_time_utc;}
        return payload;
      } catch(error){picker.replaceChildren(new Option('Candidate list unavailable — paste time manually','')); setStatus(error.message||String(error),true);return null;}
      finally{picker.disabled=false;}
    }
    async function pollRefresh(){
      try{
        const response=await fetch('/api/refresh-status'); const payload=await response.json(); if(!response.ok)throw new Error(payload.error||'Live refresh status is unavailable');
        const changed=knownDataVersion!==null&&payload.data_version!==knownDataVersion;
        refreshStatus=payload; knownDataVersion=payload.data_version; renderRefreshStamp();
        if(!changed)return;
        await loadSignals();
        request();
      }catch(error){q('asOf').textContent='Live refresh status unavailable';}
    }
    q('controls').addEventListener('submit',event=>{event.preventDefault();request();});
    q('signalPicker').addEventListener('change',()=>{if(q('signalPicker').value){q('signalTime').value=q('signalPicker').value;request();}});
    q('asset').addEventListener('change',async()=>{renderRefreshStamp();await loadSignals({preferFirst:true});request();});
    q('timeframe').addEventListener('change',async()=>{await loadSignals({preferFirst:true});request();});
    (async()=>{await pollRefresh();await loadSignals();request();window.setInterval(pollRefresh,15000);window.setInterval(renderRefreshStamp,1000);})();
  })();
  </script>
</body></html>"""


class Engine:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.lock = threading.Lock()
        self.scenario_cache: dict[tuple[str, str, str, tuple[int, ...]], dict[str, Any]] = {}
        self.frame_cache: dict[tuple[str, str, int], pd.DataFrame] = {}
        self.v2_model_path = root / "data" / "conditional_path_library_5y" / "v2_models" / "conditional_wick_v2_model.pkl"
        self.v2_summary_path = root / "data" / "conditional_path_library_5y" / "v2_models" / "conditional_wick_v2_summary.json"
        self.v2_model: dict[str, Any] | None = None
        self.v2_model_mtime_ns: int | None = None
        self.v2_load_error: str | None = None
        self.v2_summary: dict[str, Any] | None = None
        self.v2_summary_mtime_ns: int | None = None

    def _source_path(self, asset: str) -> Path:
        return self.root / "data" / f"{asset}_5m_5y.csv"

    def _stamp(self, asset: str) -> tuple[int, ...]:
        source = self._source_path(asset)
        episodes = self.root / "data" / "conditional_path_library_5y" / "episodes.csv"
        model_stamp = self.v2_model_path.stat().st_mtime_ns if self.v2_model_path.exists() else 0
        summary_stamp = self.v2_summary_path.stat().st_mtime_ns if self.v2_summary_path.exists() else 0
        return (source.stat().st_mtime_ns, episodes.stat().st_mtime_ns, model_stamp, summary_stamp)

    def _frame(self, asset: str, timeframe: str) -> pd.DataFrame:
        source = self._source_path(asset)
        # The updater swaps CSVs atomically.  Recheck its generation after the
        # read so an API request never stores a new frame under an old key.
        for _ in range(2):
            source_mtime_ns = source.stat().st_mtime_ns
            key = (asset, timeframe, source_mtime_ns)
            with self.lock:
                cached = self.frame_cache.get(key)
            if cached is not None:
                return cached
            raw = read_five_minute_file(source)
            if source.stat().st_mtime_ns != source_mtime_ns:
                continue
            frame = raw if timeframe == "5m" else resample_to_fifteen_minutes(raw)
            with self.lock:
                self.frame_cache[key] = frame
            return frame
        raise RuntimeError(f"{asset} source changed while the dashboard was loading it; retry once refresh completes")

    def invalidate_source_caches(self) -> None:
        """Release old source generations after a successful atomic refresh."""
        with self.lock:
            self.scenario_cache.clear()
            self.frame_cache.clear()

    def _v2_bundle(self) -> tuple[dict[str, Any] | None, str | None]:
        """Load the standalone V2a artifact once, without making V1 depend on it."""
        if not self.v2_model_path.exists():
            return None, "V2a model artifact is not present. Rebuild the V2 calibration artifacts first."
        model_mtime_ns = self.v2_model_path.stat().st_mtime_ns
        with self.lock:
            if self.v2_model is not None and self.v2_model_mtime_ns == model_mtime_ns:
                return self.v2_model, None
            if self.v2_load_error is not None and self.v2_model_mtime_ns == model_mtime_ns:
                return None, self.v2_load_error
        try:
            model = load_model_bundle(self.v2_model_path)
        except Exception as error:  # pragma: no cover - defensive artifact boundary
            message = f"V2a artifact could not be loaded: {type(error).__name__}"
            with self.lock:
                self.v2_model = None
                self.v2_model_mtime_ns = model_mtime_ns
                self.v2_load_error = message
            return None, message
        with self.lock:
            self.v2_model = model
            self.v2_model_mtime_ns = model_mtime_ns
            self.v2_load_error = None
        return model, None

    def _v2_summary_payload(self) -> dict[str, Any]:
        if not self.v2_summary_path.exists():
            return {}
        summary_mtime_ns = self.v2_summary_path.stat().st_mtime_ns
        with self.lock:
            if self.v2_summary is not None and self.v2_summary_mtime_ns == summary_mtime_ns:
                return self.v2_summary
        try:
            summary = json.loads(self.v2_summary_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return {}
        with self.lock:
            self.v2_summary = summary
            self.v2_summary_mtime_ns = summary_mtime_ns
        return summary

    def _v2_observable_state(self, asset: str, signal_time_ms: int) -> dict[str, Any]:
        """Build V2a inputs strictly from the candle data visible at the live snapshot."""
        frame = self._frame(asset, "5m")
        signals = detect_strict_signals(frame, asset, "5m")
        matches = signals.loc[signals["open_time"].eq(signal_time_ms)]
        if len(matches) != 1:
            raise ValueError("Pinned signal is not a unique strict 5m wick in the source snapshot")
        signal = matches.iloc[0]
        signal_index = int(signal["bar_index"])
        current_index = len(frame) - 1
        if signal_index >= current_index:
            raise ValueError("V2a needs at least one completed 5m candle after the pinned signal")
        target = float(signal["wick_target"])
        direction_sign = int(signal["direction_sign"])
        observed = frame.iloc[signal_index : current_index + 1]
        normalized_open = np.asarray(
            normalized_price(observed["open"].to_numpy(dtype=float), target, direction_sign), dtype=float
        )
        normalized_high = np.asarray(
            normalized_price(observed["high"].to_numpy(dtype=float), target, direction_sign), dtype=float
        )
        normalized_low = np.asarray(
            normalized_price(observed["low"].to_numpy(dtype=float), target, direction_sign), dtype=float
        )
        normalized_close = np.asarray(
            normalized_price(observed["close"].to_numpy(dtype=float), target, direction_sign), dtype=float
        )
        current_state = state_for_live_path(
            frame, signal_index, current_index, direction_sign, target, interval_minutes=5
        )
        close_changes = np.diff(normalized_close, prepend=normalized_close[0])
        volume_ratio = max(float(frame["volume"].iat[current_index]), 0.0) / max(
            float(frame["volume"].iat[signal_index]), 1e-12
        )
        state: dict[str, Any] = {
            "asset": asset,
            "direction": str(signal["direction"]),
            **{key: float(value) for key, value in current_state.items() if key != "elapsed_minutes"},
            "current_bar_range_pct": float(abs(normalized_high[-1] - normalized_low[-1])),
            "current_bar_body_pct": float(abs(normalized_close[-1] - normalized_open[-1])),
            "recent_bar_range_mean_3_pct": float(np.mean(np.abs(normalized_high[-3:] - normalized_low[-3:]))),
            "recent_abs_close_change_mean_3_pct": float(np.mean(np.abs(close_changes[-3:]))),
            "volume_ratio_to_signal": float(volume_ratio),
        }
        for feature in FEATURE_COLUMNS:
            state[feature] = float(signal[feature])
        return state

    def _v2_risk(self, asset: str, timeframe: str, signal_time_ms: int) -> dict[str, Any]:
        """Return optional V2a risk quantiles; V1 paths remain available if this is unavailable."""
        if timeframe != "5m":
            return {
                "available": False,
                "reason": "V2a is currently trained and calibrated only on 5m BTCUSDT/ETHUSDT snapshots. V1 routes still use the selected timeframe.",
            }
        model, model_error = self._v2_bundle()
        if model is None:
            return {"available": False, "reason": model_error or "V2a model artifact is unavailable."}
        try:
            observable_state = self._v2_observable_state(asset, signal_time_ms)
            prediction = predict_from_observable_state(model, observable_state)
        except (KeyError, TypeError, ValueError) as error:
            return {"available": False, "reason": f"V2a could not construct a valid observable state: {error}"}

        summary = self._v2_summary_payload()
        calibration = summary.get("calibration", {})
        snapshot_offsets = [int(value) for value in summary.get("data", {}).get("snapshot_offsets_bars", [])]
        max_snapshot_offset = max(snapshot_offsets) if snapshot_offsets else None
        remaining = calibration.get("remaining_bars", {})
        future_away = calibration.get("future_max_away_pct", {})
        future_p10 = next(
            (
                row.get("observed_coverage")
                for row in future_away.get("coverage_by_quantile", [])
                if float(row.get("quantile", -1)) == 0.10
            ),
            None,
        )
        return {
            "available": True,
            "name": "V2a calibrated conditional ranges",
            "estimator": model.get("estimator", "local conditional quantiles"),
            "prediction": prediction,
            "observable_state": {key: round(float(value), 8) for key, value in observable_state.items() if key not in {"asset", "direction"}},
            "calibration": {
                "holdout_snapshot_count": future_away.get("case_count"),
                "remaining_p10_p90_observed_coverage": remaining.get("p10_to_p90_interval_observed_coverage"),
                "future_away_p10_p90_observed_coverage": future_away.get("p10_to_p90_interval_observed_coverage"),
                "future_away_p10_observed_coverage": future_p10,
            },
            "state_coverage": {
                "elapsed_bars": int(observable_state["elapsed_bars"]),
                "training_snapshot_offsets_bars": snapshot_offsets,
                "max_training_snapshot_elapsed_bars": max_snapshot_offset,
                "elapsed_within_training_snapshot_range": (
                    None if max_snapshot_offset is None else int(observable_state["elapsed_bars"]) <= max_snapshot_offset
                ),
            },
            "warning": "Conditional clean-fill diagnostic only. Future move-away P10 under-covered in the chronological holdout, so it is never a sizing floor or risk limit.",
        }

    def available_unfilled_signals(self, asset: str, timeframe: str) -> dict[str, Any]:
        frame = self._frame(asset, timeframe)
        signals = detect_strict_signals(frame, asset, timeframe)
        items: list[dict[str, Any]] = []
        # The tail is enough for a practical pin picker and prevents a costly
        # full-history scan every time the browser asks for candidates.
        for signal in signals.tail(400).iloc[::-1].itertuples(index=False):
            index = int(signal.bar_index)
            if index >= len(frame) - 1:
                continue
            target = float(signal.wick_target)
            direction_sign = int(signal.direction_sign)
            later = frame.iloc[index + 1 :]
            filled = (later["low"] <= target).any() if direction_sign == 1 else (later["high"] >= target).any()
            if filled:
                continue
            departed = (later["close"] > float(signal.high)).any() if direction_sign == 1 else (
                later["close"] < float(signal.low)
            ).any()
            if not departed:
                continue
            state = state_for_live_path(frame, index, len(frame) - 1, direction_sign, target, int(signal.interval_minutes))
            if state["current_move_pct"] <= 0:
                continue
            items.append(
                {
                    "signal_time_utc": utc_iso(int(signal.open_time)),
                    "direction": str(signal.direction),
                    "wick_target": target,
                    "current_move_pct": round(float(state["current_move_pct"]), 4),
                    "elapsed_minutes": int(state["elapsed_minutes"]),
                }
            )
            if len(items) >= 80:
                break
        return {
            "asset": asset,
            "timeframe": timeframe,
            "as_of_open_time_utc": utc_iso(int(frame["open_time"].iat[-1])),
            "signals": items,
        }

    def scenarios(self, asset: str, timeframe: str, signal_time: str) -> dict[str, Any]:
        if asset not in ASSETS or timeframe not in TIMEFRAMES:
            raise ValueError("asset must be ETHUSDT/BTCUSDT and timeframe must be 5m/15m")
        # Parse before starting a subprocess, so malformed browser input cannot
        # become a command argument with ambiguous time semantics.
        signal_time_ms = parse_utc(signal_time)
        stamp = self._stamp(asset)
        key = (asset, timeframe, signal_time, stamp)
        with self.lock:
            cached = self.scenario_cache.get(key)
        if cached is not None:
            return cached
        with tempfile.TemporaryDirectory(prefix="conditional-wick-") as directory:
            output = Path(directory) / "scenario.json"
            command = [
                sys.executable,
                str(self.root / "build_conditional_path_scenarios.py"),
                "--asset",
                asset,
                "--timeframe",
                timeframe,
                "--signal-time",
                signal_time,
                "--top-k",
                "80",
                "--output",
                str(output),
            ]
            result = subprocess.run(command, cwd=self.root, capture_output=True, text=True, timeout=180, check=False)
            if result.returncode != 0:
                detail = (result.stderr or result.stdout or "The scenario engine failed.").strip().splitlines()[-1]
                raise ValueError(detail[:500])
            payload = json.loads(output.read_text(encoding="utf-8"))
        payload["v2_risk"] = self._v2_risk(asset, timeframe, signal_time_ms)
        with self.lock:
            self.scenario_cache[key] = payload
        return payload


ENGINE = Engine(ROOT)


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


class LiveRefreshCoordinator:
    """Keep local completed-candle sources current while the dashboard runs."""

    def __init__(self, engine: Engine, interval_seconds: int, enabled: bool, refresh_close_guard_seconds: int = 5) -> None:
        if interval_seconds < 60:
            raise ValueError("refresh interval must be at least 60 seconds")
        if refresh_close_guard_seconds < 0 or refresh_close_guard_seconds >= interval_seconds:
            raise ValueError("refresh close guard must be non-negative and shorter than the interval")
        self.engine = engine
        self.interval_seconds = interval_seconds
        self.enabled = enabled
        self.refresh_close_guard_seconds = refresh_close_guard_seconds
        self.lock = threading.Lock()
        self.stop_event = threading.Event()
        self.thread: threading.Thread | None = None
        self.state: dict[str, Any] = {
            "enabled": enabled,
            "interval_seconds": interval_seconds,
            "refresh_close_guard_seconds": refresh_close_guard_seconds,
            "in_progress": False,
            "last_attempt_utc": None,
            "last_success_utc": None,
            "last_error": None,
            "next_refresh_utc": None,
            "last_results": {},
        }

    def _seconds_until_next_boundary(self) -> float:
        now = time.time()
        next_boundary = (
            (int((now - self.refresh_close_guard_seconds) // self.interval_seconds) + 1) * self.interval_seconds
            + self.refresh_close_guard_seconds
        )
        return max(1.0, next_boundary - now)

    def _set_next_refresh(self) -> None:
        if not self.enabled:
            return
        next_timestamp = time.time() + self._seconds_until_next_boundary()
        next_iso = datetime.fromtimestamp(next_timestamp, tz=timezone.utc).replace(microsecond=0).isoformat().replace(
            "+00:00", "Z"
        )
        with self.lock:
            self.state["next_refresh_utc"] = next_iso

    def start(self) -> None:
        if not self.enabled or self.thread is not None:
            return
        self.thread = threading.Thread(target=self._run, name="conditional-wick-live-refresh", daemon=True)
        self.thread.start()

    def stop(self) -> None:
        self.stop_event.set()
        if self.thread is not None:
            self.thread.join(timeout=1.0)

    def _run(self) -> None:
        # Refresh immediately to catch up a server restarted between five-minute
        # boundaries, then align every later attempt to the next boundary.
        while not self.stop_event.is_set():
            self.refresh_once()
            self._set_next_refresh()
            if self.stop_event.wait(self._seconds_until_next_boundary()):
                break

    def refresh_once(self) -> bool:
        """Refresh both source files once.  A single failed asset keeps its old CSV."""
        if not self.enabled:
            return False
        with self.lock:
            if self.state["in_progress"]:
                return False
            self.state["in_progress"] = True
            self.state["last_attempt_utc"] = _utc_now_iso()
            self.state["last_error"] = None

        results: dict[str, dict[str, Any]] = {}
        changed = False
        errors: list[str] = []
        try:
            try:
                shared_server_time_ms = exchange_server_time_ms()
            except Exception as error:
                message = f"{type(error).__name__}: {error}"
                for asset in ASSETS:
                    results[asset] = {"ok": False, "error": f"Binance server time unavailable: {message}"}
                errors.append(f"Binance server time: {message}")
            else:
                for asset in ASSETS:
                    try:
                        result: RefreshResult = refresh_source(
                            asset,
                            self.engine._source_path(asset),
                            interval="5m",
                            server_time_ms=shared_server_time_ms,
                        )
                        result_payload = result.as_payload()
                        results[asset] = {"ok": True, **result_payload}
                        changed = changed or result.changed
                    except Exception as error:  # Keep the last verified source intact and expose the exact asset status.
                        message = f"{type(error).__name__}: {error}"
                        results[asset] = {"ok": False, "error": message}
                        errors.append(f"{asset}: {message}")
            if changed:
                self.engine.invalidate_source_caches()
        finally:
            finished_at = _utc_now_iso()
            with self.lock:
                self.state["in_progress"] = False
                self.state["last_results"] = results
                self.state["last_error"] = "; ".join(errors) if errors else None
                if not errors:
                    self.state["last_success_utc"] = finished_at
        return changed

    def status(self) -> dict[str, Any]:
        with self.lock:
            payload = dict(self.state)
            results = dict(self.state["last_results"])
        sources: dict[str, dict[str, Any]] = {}
        version_parts: list[str] = []
        for asset in ASSETS:
            source = self.engine._source_path(asset)
            try:
                snapshot = source_snapshot(source)
                source_payload = snapshot.as_payload()
                sources[asset] = {
                    "available": True,
                    "last_closed_candle_open_time_utc": source_payload["last_closed_candle_open_time_utc"],
                    "source_mtime_ns": snapshot.mtime_ns,
                    "last_rows_added": results.get(asset, {}).get("rows_added"),
                    "last_refresh_result": results.get(asset),
                }
                version_parts.append(f"{asset}:{snapshot.mtime_ns}")
            except Exception as error:  # pragma: no cover - defensive status boundary
                sources[asset] = {"available": False, "error": f"{type(error).__name__}: {error}"}
                version_parts.append(f"{asset}:unavailable")
        payload["data_version"] = "|".join(version_parts)
        payload["sources"] = sources
        return payload


class Handler(BaseHTTPRequestHandler):
    server_version = "ConditionalWickDashboard/1.0"

    def _json(self, payload: dict[str, Any], status: HTTPStatus = HTTPStatus.OK) -> None:
        encoded = json.dumps(payload, separators=(",", ":"), allow_nan=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(encoded)

    def _html(self) -> None:
        encoded = HTML.encode("utf-8")
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(encoded)

    def do_GET(self) -> None:  # noqa: N802 - required by BaseHTTPRequestHandler
        parsed = urlparse(self.path)
        query = parse_qs(parsed.query)
        try:
            if parsed.path == "/":
                self._html()
            elif parsed.path == "/api/health":
                refresher = getattr(self.server, "refresh_coordinator", None)
                self._json(
                    {
                        "ok": True,
                        "service": self.server_version,
                        "default": DEFAULT_SIGNAL,
                        "refresh": refresher.status() if refresher is not None else {"enabled": False},
                    }
                )
            elif parsed.path == "/api/refresh-status":
                refresher = getattr(self.server, "refresh_coordinator", None)
                if refresher is None:
                    raise ValueError("Live refresh coordinator is not configured")
                self._json(refresher.status())
            elif parsed.path == "/api/signals":
                asset = query.get("asset", [DEFAULT_SIGNAL["asset"]])[0]
                timeframe = query.get("timeframe", [DEFAULT_SIGNAL["timeframe"]])[0]
                if asset not in ASSETS or timeframe not in TIMEFRAMES:
                    raise ValueError("asset must be ETHUSDT/BTCUSDT and timeframe must be 5m/15m")
                self._json(ENGINE.available_unfilled_signals(asset, timeframe))
            elif parsed.path == "/api/scenarios":
                asset = query.get("asset", [DEFAULT_SIGNAL["asset"]])[0]
                timeframe = query.get("timeframe", [DEFAULT_SIGNAL["timeframe"]])[0]
                signal_time = query.get("signal_time", [DEFAULT_SIGNAL["signal_time"]])[0]
                self._json(ENGINE.scenarios(asset, timeframe, signal_time))
            elif parsed.path == "/favicon.ico":
                self.send_response(HTTPStatus.NO_CONTENT)
                self.end_headers()
            else:
                self._json({"error": "Not found"}, HTTPStatus.NOT_FOUND)
        except (ValueError, FileNotFoundError) as error:
            self._json({"error": str(error)}, HTTPStatus.BAD_REQUEST)
        except subprocess.TimeoutExpired:
            self._json({"error": "Scenario search exceeded 180 seconds; retry once the local machine is less busy."}, HTTPStatus.GATEWAY_TIMEOUT)
        except Exception as error:  # pragma: no cover - defensive HTTP boundary
            self._json({"error": f"Internal dashboard error: {type(error).__name__}"}, HTTPStatus.INTERNAL_SERVER_ERROR)

    def log_message(self, format: str, *args: Any) -> None:
        print(f"[{self.log_date_time_string()}] {format % args}", flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8793)
    parser.add_argument(
        "--refresh-seconds",
        type=int,
        default=300,
        help="Completed-candle refresh cadence while the service runs (default: 300).",
    )
    parser.add_argument(
        "--disable-auto-refresh",
        action="store_true",
        help="Serve the existing local source without contacting Binance; useful for deterministic replay.",
    )
    parser.add_argument(
        "--refresh-close-guard-seconds",
        type=int,
        default=5,
        help="Wait this many seconds after each five-minute boundary before polling Binance (default: 5).",
    )
    args = parser.parse_args()
    server = ThreadingHTTPServer((args.host, args.port), Handler)
    server.daemon_threads = True
    refresher = LiveRefreshCoordinator(
        ENGINE,
        args.refresh_seconds,
        enabled=not args.disable_auto_refresh,
        refresh_close_guard_seconds=args.refresh_close_guard_seconds,
    )
    server.refresh_coordinator = refresher
    refresher.start()
    print(
        json.dumps(
            {
                "url": f"http://{args.host}:{args.port}/",
                "default_signal": DEFAULT_SIGNAL,
                "refresh_seconds": args.refresh_seconds,
                "refresh_close_guard_seconds": args.refresh_close_guard_seconds,
                "auto_refresh": not args.disable_auto_refresh,
            }
        ),
        flush=True,
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        refresher.stop()
        server.server_close()


if __name__ == "__main__":
    main()
